default: &default
  adapter: postgresql
  encoding: unicode
  pool: "<%= ENV.fetch('MAX_THREADS', 5) %>"
  port: "<%= ENV.fetch('POSTGRES_PORT', '5432') %>"
  username: "<%= ENV.fetch('DB_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('DB_PASSWORD', 'password') %>"
  host: "<%= ENV.fetch('DB_HOST', 'localhost') %>"

development:
  <<: *default
  database: torn_app_development

test:
  <<: *default
  database: torn_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: torn_app_production
